# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nushell.Nushell
PackageVersion: 0.116.0
InstallerLocale: en-US
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- nu
ReleaseDate: 2026-09-26
InstallationMetadata:
  DefaultInstallLocation: nu
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.0/nu-0.116.0-x86_64-pc-windows-msvc.msi
  InstallerSha256: 207D91EB1CAE3FFF4B5B4A2CCDDE9E706879BF1AF669EA70182B29EB7CD53FB7
  InstallerSwitches:
    Custom: ALLUSERS=2 MSIINSTALLPERUSER=1
  ProductCode: '{431E9565-1FC3-4ED2-BDC8-69D4B68C8CBB}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{431E9565-1FC3-4ED2-BDC8-69D4B68C8CBB}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.0/nu-0.116.0-x86_64-pc-windows-msvc.msi
  InstallerSha256: 207D91EB1CAE3FFF4B5B4A2CCDDE9E706879BF1AF669EA70182B29EB7CD53FB7
  InstallerSwitches:
    Custom: ALLUSERS=1
  ProductCode: '{431E9565-1FC3-4ED2-BDC8-69D4B68C8CBB}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{431E9565-1FC3-4ED2-BDC8-69D4B68C8CBB}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.0/nu-0.116.0-aarch64-pc-windows-msvc.msi
  InstallerSha256: EC44101F52E1641DDC9A22BF344C883F9B4F18F750E26EBD071FB97111513E87
  InstallerSwitches:
    Custom: ALLUSERS=2 MSIINSTALLPERUSER=1
  ProductCode: '{C0EE53BC-DC0A-447E-911C-5F4AE73F67F3}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{C0EE53BC-DC0A-447E-911C-5F4AE73F67F3}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/nushell/nushell/releases/download/0.116.0/nu-0.116.0-aarch64-pc-windows-msvc.msi
  InstallerSha256: EC44101F52E1641DDC9A22BF344C883F9B4F18F750E26EBD071FB97111513E87
  InstallerSwitches:
    Custom: ALLUSERS=1
  ProductCode: '{C0EE53BC-DC0A-447E-911C-5F4AE73F67F3}'
  AppsAndFeaturesEntries:
  - DisplayName: Nushell
    ProductCode: '{C0EE53BC-DC0A-447E-911C-5F4AE73F67F3}'
    UpgradeCode: '{82D756D2-19FA-4F09-B10F-64942E89F364}'
ManifestType: installer
ManifestVersion: 1.12.0
