# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OnjLouis.SensorReadout
PackageVersion: 6.3.2
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: exe
Scope: user
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --install-silent
  SilentWithProgress: --install-silent
UpgradeBehavior: install
FileExtensions:
- srconnection
ProductCode: Sensor Readout
ElevationRequirement: elevationRequired
AppsAndFeaturesEntries:
- DisplayName: Sensor Readout
  Publisher: Andre Louis
  DisplayVersion: 6.3.2
  ProductCode: Sensor Readout
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: Sensor Readout.exe
  InstallerUrl: https://github.com/OnjLouis/accessible-sensor-readout/releases/download/v6.3.2/SensorReadout-6.3.2.zip
  InstallerSha256: C99D4BF75F2ED349E6CF34FFB24A79AC54016B851E0CF12FFDF3061A44186CBB
ManifestType: installer
ManifestVersion: 1.12.0
