# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: BrunoVolpato.ivygrep
PackageVersion: 1.3.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ivygrep-v1.3.0-windows-x86_64/ig.exe
  PortableCommandAlias: ig
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bvolpato/ivygrep/releases/download/v1.3.0/ivygrep-v1.3.0-windows-x86_64.zip
  InstallerSha256: 9305FAAC55ADCC36425C6351A56E29BB3919FEB80A69DBC3B42E443D536D15EA
ManifestType: installer
ManifestVersion: 1.12.0
