# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GregorDadera.AIContextBuilder
PackageVersion: 0.5.464.56
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
ElevationRequirement: elevationRequired
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/gregordadera/AICB/releases/download/v0.5.464.56/AIContextBuilder-Setup-0.5.464.56.exe
  InstallerSha256: 96B6EAA157212D1BA66ECC5A938142614EBC63CC1BE277FB4B9EB1323BF819A0
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ManifestType: installer
ManifestVersion: 1.12.0
