# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: BlackwellSystems.agent-lsp
PackageVersion: 0.20.0
Platform:
- Windows.Desktop
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: agent-lsp.exe
  PortableCommandAlias: agent-lsp
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/blackwell-systems/agent-lsp/releases/download/v0.20.0/agent-lsp_windows_amd64.zip
  InstallerSha256: 0F8AE1D0409135F189A77ED6B63BE2A61EF92063E46E71141F1A856229D52159
- Architecture: arm64
  InstallerUrl: https://github.com/blackwell-systems/agent-lsp/releases/download/v0.20.0/agent-lsp_windows_arm64.zip
  InstallerSha256: FAF3C5D3EBC371E794FC4DE6E94654FFA70B586B018B2645825ED5D0F3A53871
ManifestType: installer
ManifestVersion: 1.12.0
