# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: lanxiuyun.Catrace
PackageVersion: 26.9.26
InstallerType: nullsoft
Scope: user
ProductCode: Catrace
ReleaseDate: 2026-09-26
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Catrace'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/lanxiuyun/Catrace/releases/download/v26.9.26/Catrace_26.9.26_x64-setup.exe
  InstallerSha256: D0A8112B009B59630154E0E848591B7F4A3E980E059694DCBEA9D6CDD0CF2168
ManifestType: installer
ManifestVersion: 1.12.0
