# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Proxyman.Proxyman
PackageVersion: 3.21.0
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
FileExtensions:
- har
- proxymanlogv2
ProductCode: 1c658a2b-63bd-5737-96bf-d2b01fd7d360
ReleaseDate: 2026-09-25
Installers:
- Architecture: x64
  InstallerUrl: https://assets.proxyman.com/windows/3.21.0/build/Proxyman%20Setup%203.21.0.exe
  InstallerSha256: 0FC4FD7AC1073E5D0248E61C3D2704E2B21747A96CF183FE35578A437377B898
ManifestType: installer
ManifestVersion: 1.12.0
