# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: MarcoSburlino.Koinkat
PackageVersion: 0.1.6
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17134.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/MarcoSburlino/Koinkat/releases/download/v0.1.6/Koinkat_0.1.6_x64-setup.exe
  InstallerSha256: FA81DD6D22642412DA1208F425DE3E6BBB197D2FF9984EF956DCA15A3824C1A7
ManifestType: installer
ManifestVersion: 1.6.0
