# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: blakazulu.Findra
PackageVersion: 0.5.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /INSTALLSOURCE=winget
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.5.0/findra-setup-x64.exe
  InstallerSha256: 3CB1BD91C757A2DABFC97BF8B9E168E1DA0FD121DEF58638525F9430222C7899
- Architecture: arm64
  InstallerUrl: https://github.com/blakazulu/findra/releases/download/v0.5.0/findra-setup-arm64.exe
  InstallerSha256: 1C41EE11D3DCE8C968155719A18E4CF6DFAC16D3CFA0FA7443D4514F651D1130
ManifestType: installer
ManifestVersion: 1.6.0
