# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MartinBresson.Executor
PackageVersion: 2.4.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: Executor_is1
ReleaseDate: 2026-09-26
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Executor'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/executordk/executor-community/releases/download/v2.4.0/ExecutorSetup_v2.4.0.exe
  InstallerSha256: FCA47B6E174F9418008D04D45D8289935FD4AE76B12093EC780A74E0057AFDCB
ManifestType: installer
ManifestVersion: 1.12.0
