# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: MartinBresson.Executor
PackageVersion: 2.4.0
PackageLocale: en-US
Publisher: Martin Bresson
PublisherUrl: https://catswithfunnyhats.com/
PublisherSupportUrl: https://github.com/executordk/executor-community/issues
Author: Martin Bresson
PackageName: Executor
PackageUrl: https://executor.dk/
License: Freeware
Copyright: Copyright © 2007-2026 Martin Bresson.
ShortDescription: Executor the desktop workflow application for Windows. Speed up your daily workflow, opening things and doing things.
Description: |-
  Executor the desktop workflow application for Windows. Speed up your daily workflow, opening things and doing things.

  Key Features:
  - Launch applications, files, folders, websites, web services (with parameters) and prompts in milliseconds.
  - Trigger multiple actions with one text command and/or hotkey.
  - Let's be an expert in opening up the world instead of trying to put the whole world inside of Executor (as some alternatives try to do).
  - Take the clipboard to a new level, swiftly trigger system commands, do fast calculations, manage running applications and more.
  - Tailor keywords, appearance, hotkeys, and behavior to perfectly match your daily workflow.
  - Customize the look and feel with various skins and theming options to match your desktop setup.
Tags:
- ai
- desktop
- launcher
- workflow
ReleaseNotes: |-
  What's new
  - Need to research an embarrassing topic, or have someone looking over your shoulder? You can now enable Incognito mode, that per default will not add anything to history while enabled. You can further configure the incognito mode to do one or more of the following:
    - Hide history from auto-complete and list (file system, URLs, keywords).
    - Hide all list entries either when input is empty or all time time.
    - Disable file navigation in list.
    - Disable clipboard sniffer.
    - Disable input assist.
    - Hide tags.
    - Use a clean temporary session for internal browser.
    Incognito configuration is stored in the setting incognitoconfig. More details and list of configuration values here.
  - Added a new keyword incognito that can be imported from default.exc (type imports). This uses the new $INCOGNITO$ keyword command. Keyword syntax: [on,off,?,(empty=toggle),[config]].
    Examples of use:
    - incognito - will turn incognito mode on/off
    - incognito on - turn on
    - incognito off - turn off
    - incognito ? - list current config value (example "14ib")
    - incognito 25cb - will change the incognito config to 25cb
    - incognito on,36i - will turn on mode and set incognito config to 36i
    By being able to set incognitoconfig as a parameter it allows you to make keywords that turns on incognito mode with a certain configuration preset, see this example screenshot. Also an "I" will be displayed while incognito mode is active (protip: change color of this using setting toastfontcolor).
  Improvements
  - The keyword editor now has a "+ New" button in the upper right corner to add a keyword (besides using the right-click menu or insert key to add a keyword).
  - In the Keyword Editor the keyword properties panel is now hidden when no keyword is selected. In case you liked that the keyword panel is always visible, even when empty, you can re-enable this with the setting hidekeywordpanel.
  - In the Keyword Editor the keyword properties panel can be dismissed by clicking a close button in the upper-right corner, this will give more keyword-list space.
  Other notes
  - Check out the new video Tips And Tricks Volume #1 (unrelated to the updates in this release).
ReleaseNotesUrl: https://executor.dk/updates#v2400
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://executor.dk/docs
- DocumentLabel: Tips & tricks
  DocumentUrl: https://executor.dk/tips
- DocumentLabel: Community
  DocumentUrl: https://github.com/executordk/executor-community/discussions
ManifestType: defaultLocale
ManifestVersion: 1.12.0
