# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Drawpile.Drawpile
PackageVersion: 2.3.0
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-11-19
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/drawpile/Drawpile/releases/download/2.3.0/Drawpile-2.3.0-x86.msi
  InstallerSha256: 821806F6F738F4B34C5C81C65D4FF45AF5AA6E2059C349705605F41993CD5699
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
      MinimumVersion: 14.51.36247.0
  ProductCode: '{4F1316E0-2B1D-4BF1-81DF-CBC60FA02669}'
  AppsAndFeaturesEntries:
  - Publisher: Drawpile contributors
    ProductCode: '{4F1316E0-2B1D-4BF1-81DF-CBC60FA02669}'
    UpgradeCode: '{DC47B534-E365-4054-85F0-2E7C6CCB76CC}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%/Drawpile'
- Architecture: x64
  InstallerUrl: https://github.com/drawpile/Drawpile/releases/download/2.3.0/Drawpile-2.3.0-x86_64.msi
  InstallerSha256: CC3555D0AF30EC2081F80AF1EE6FC1DAB49129CB20E750320C56E1D7A1E29639
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
      MinimumVersion: 14.51.36247.0
  ProductCode: '{09D7941B-505D-47CF-B388-F8EAB622FE23}'
  AppsAndFeaturesEntries:
  - Publisher: Drawpile contributors
    ProductCode: '{09D7941B-505D-47CF-B388-F8EAB622FE23}'
    UpgradeCode: '{DC47B534-E365-4054-85F0-2E7C6CCB76CC}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Drawpile'
- Architecture: arm64
  InstallerUrl: https://github.com/drawpile/Drawpile/releases/download/2.3.0/Drawpile-2.3.0-arm64.msi
  InstallerSha256: 570072C0DA2F684448B23C5910F6037B8117C2E4E6E14AD48F7079BE926901EF
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
      MinimumVersion: 14.51.36247.0
  ProductCode: '{4DFD590E-31BF-4BBF-8742-B3F107B5396F}'
  AppsAndFeaturesEntries:
  - Publisher: Drawpile contributors
    ProductCode: '{4DFD590E-31BF-4BBF-8742-B3F107B5396F}'
    UpgradeCode: '{DC47B534-E365-4054-85F0-2E7C6CCB76CC}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/Drawpile'
ManifestType: installer
ManifestVersion: 1.10.0
