# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.SafetyScanner
PackageVersion: 1.459.418.0
InstallerType: portable
Commands:
- safetyscanner
ReleaseDate: 2026-09-26
Installers:
- Architecture: x86
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.418.0&arch=x86
  InstallerSha256: B9E9C474B4EAD98577D7C18ACBAE244A58C387184DFB13A317DBDBEC7B36EF00
- Architecture: x64
  InstallerUrl: https://definitionupdates.microsoft.com/packages/content/msert.exe?packageType=Scanner&packageVersion=1.459.418.0&arch=amd64
  InstallerSha256: 0BC6DA9D99973C069896676201F1104BEDA62E7009B46122F9B452A146098B65
ManifestType: installer
ManifestVersion: 1.12.0
