# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: OpenGeos.GeoLibre
PackageVersion: 3.1.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/opengeos/GeoLibre/releases/download/v3.1.0/GeoLibre.Desktop_3.1.0_x64-setup.exe
  InstallerSha256: 150C5E544B8A185C2B88904F7C3881018CEBD9501B02F689613D0B66B9EE0E6F
ManifestType: installer
ManifestVersion: 1.12.0
