# Created by Anthelion using komac v2.17.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: xAI.GrokBot
PackageVersion: 0.59.1
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: 8db316bb-b3e2-5dd2-9554-ecccb62be362
ReleaseDate: 2026-09-26
AppsAndFeaturesEntries:
- ProductCode: 8db316bb-b3e2-5dd2-9554-ecccb62be362
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.cursor.com/grokbot/stable/win32-x64/0.59.1/Grok_Bot_0.59.1_Setup.exe
  InstallerSha256: BC4E0CB1E39EB894FF51F1A56A2A43829BA335AE889133767E5CEB0A764CD85E
- Architecture: arm64
  InstallerUrl: https://downloads.cursor.com/grokbot/stable/win32-arm64/0.59.1/Grok_Bot_0.59.1_Setup.exe
  InstallerSha256: 4DC9EAD21C2D726594D3531025BF69ABC617021021450E6B11ABF7BD33ED21C6
ManifestType: installer
ManifestVersion: 1.12.0
