# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sysmanage.sysmanage
PackageVersion: 3.9.0.13
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.9.0.13/sysmanage-3.9.0.13-windows-x64.msi
  InstallerSha256: 3F80759F942E2331F0A4F26B33E17D89172D782CE92F2453A209CD836FF49BE8
  ProductCode: '{44F9276A-7CD8-4733-9DD8-183A8F58E4B2}'
  AppsAndFeaturesEntries:
  - ProductCode: '{44F9276A-7CD8-4733-9DD8-183A8F58E4B2}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
- Architecture: arm64
  InstallerUrl: https://github.com/bceverly/sysmanage/releases/download/v3.9.0.13/sysmanage-3.9.0.13-windows-arm64.msi
  InstallerSha256: EE31CE5C30BB4669379A3AAEC95E3225E4952A36F36CA2FC905E71186B500F16
  ProductCode: '{A35F10CA-79F9-4F67-B620-112AE745E048}'
  AppsAndFeaturesEntries:
  - ProductCode: '{A35F10CA-79F9-4F67-B620-112AE745E048}'
    UpgradeCode: '{F1E2D3C4-B5A6-4D7C-9E8F-1A2B3C4D5E6F}'
ManifestType: installer
ManifestVersion: 1.12.0
